### ISSUE TITLE
How use oven filter?

### ISSUE THREAD

**Issue by MiguelAngelLV** [Andre0512/pyhOn#9]
Hi, I don't undertand how works the oven program filter.

My problem is the very long list of programs in my oven:

```yaml
settings:
  startProgram:
    delayTime:
      max: 1439
      min: 0
      step: 1
    prTime:
      max: 240
      min: 0
      step: 1
    preheatStatus:
      max: 1
      min: 0
      step: 1
    program:
      - bottom_heating
      - bottom_heating_fan
      - convection_fan
      - conventional
      - h20_clean
      - iot_guided_a_thousand_leaves
      - iot_guided_apple_pie
      - iot_guided_baked_apples
      - iot_guided_baked_fish
      - iot_guided_baked_pasta
      - iot_guided_baked_vegetables
      - iot_guided_beef_wellington
      - iot_guided_biscuits
      - iot_guided_braised
      - iot_guided_braised_vegetables
      - iot_guided_brioches
      - iot_guided_butter_biscuits
      - iot_guided_chicken_in_pieces
      - iot_guided_cookies
      - iot_guided_cream_puffs
      - iot_guided_creme_caramel
      - iot_guided_fish_fillet
      - iot_guided_fish_souffle
      - iot_guided_fresh_cannelloni
      - iot_guided_fresh_lasagna
      - iot_guided_frozen_croissants
      - iot_guided_frozen_fish
      - iot_guided_frozen_lasagna_and_cannelloni
      - iot_guided_frozen_pizza
      - iot_guided_fruit_in_syrup
      - iot_guided_fruit_tart
      - iot_guided_leavened_cakes
      - iot_guided_macaron
      - iot_guided_meatloaf
      - iot_guided_mini_croissants_and_brioche
      - iot_guided_muffin
      - iot_guided_panettone
      - iot_guided_pastries_and_brioches
      - iot_guided_pears_cake
      - iot_guided_pizza_or_focaccia
      - iot_guided_plum_cake
      - iot_guided_potato_croquettes
      - iot_guided_pudding
      - iot_guided_rice_pie
      - iot_guided_rice_pilaf
      - iot_guided_roast_chicken
      - iot_guided_roast_pork
      - iot_guided_roasted_pig
      - iot_guided_salt_crusted_fish
      - iot_guided_salty_sheets
      - iot_guided_savoury_cake
      - iot_guided_single_portion_souffle
      - iot_guided_souffle
      - iot_guided_sponge_cake
      - iot_guided_strudel
      - iot_guided_stuffed_chicken
      - iot_guided_stuffed_peppers
      - iot_guided_stuffed_puff_pastry
      - iot_guided_sweet_puffs
      - iot_guided_terrine
      - iot_guided_vegetable_bain_marie_flan
      - iot_guided_vegetable_flan
      - iot_guided_vegetable_gratin
      - iot_guided_white_bread
      - iot_guided_whole_fish
      - iot_guided_yeast_cakes
      - iot_guided_yogurt
      - iot_recipe_5_spices_roasted_lamb_rack
      - iot_recipe_anchovy_courgette_flan
      - iot_recipe_apricot_cake_with_marzipan
      - iot_recipe_apricots_clafoutis
      - iot_recipe_artichokes_and_cream_lasagna
      - iot_recipe_asparagus_and_puff_pastry_tarte
      - iot_recipe_aubergine_pies_with_lamb_reduction_and_rice
      - iot_recipe_aubergine_salad_with_parsley
      - iot_recipe_baby_octopus_with_olives_and_tomato
      - iot_recipe_baguettes_with_olives
      - iot_recipe_baked_aubergines__mussaka_style
      - iot_recipe_baked_beetrots_gazpacho_and_capers
      - iot_recipe_baked_coq-au-vin_
      - iot_recipe_baked_duck_breast_honey_and_pears
      - iot_recipe_baked_duck_fricassee
      - iot_recipe_baked_panzerotti
      - iot_recipe_baked_pears_with_camembert_and_chives
      - iot_recipe_baked_swordfish_rolls_with_red_lentils
      - iot_recipe_barley_stew_and_lamb_fillet
      - iot_recipe_barley_stuffed_peppers_with_citrus_fruits
      - iot_recipe_basque_style_beef_with_peppers_and_tomatoes
      - iot_recipe_bass_fillets_roasted_with_lemon_and_orange
      - iot_recipe_beef_brisket_with_horseradish_sauce_and_chives_oil
      - iot_recipe_beef_satay_with_broccoli
      - iot_recipe_beetroot_and_blue_cheese_flan
      - iot_recipe_beetroot_and_gorgonzola_cheese_rice_timbale
      - iot_recipe_beetroots_and_goat_cheese_chutney
      - iot_recipe_beetroots_pancakes
      - iot_recipe_black_forest_cake
      - iot_recipe_black_pepper_curry_chicken
      - iot_recipe_black_rice_casserole_with_lamb_and_artichokes
      - iot_recipe_black_rice_with_prawns_and_scallops
      - iot_recipe_blanched_salmon_carpaccio
      - iot_recipe_blueberry_scones
      - iot_recipe_braided_yeast_bread
      - iot_recipe_braised_beef_with_stout
      - iot_recipe_braised_boar_in_red_wine
      - iot_recipe_broccoli_and_ham_flan
      - iot_recipe_brussels_sprouts_a_la_creme
      - iot_recipe_bulgur_vegetarian_couscous
      - iot_recipe_burgul_and_seitan_pancakes
      - iot_recipe_caesar_salad_with_roasted_cod
      - iot_recipe_cashew_thai_chicken
      - iot_recipe_catalan-style_lobster_medallions
      - iot_recipe_catalan_cream_and_red_berries
      - iot_recipe_cauliflower_and_broccoli_flan_in_currant_sauce
      - iot_recipe_cauliflower_and_cheese_mash
      - iot_recipe_cauliflower_souffle
      - iot_recipe_cheese_and_saffron_bread
      - iot_recipe_cheese_brisee_triangles
      - iot_recipe_cherry_tomatoes_bread_dough_baskets
      - iot_recipe_chicken_biryani
      - iot_recipe_chicken_cacciatore
      - iot_recipe_chicken_casserole_with_mustard_lemon_and_honey
      - iot_recipe_chicken_cream_rolls
      - iot_recipe_chicken_samsa
      - iot_recipe_chicken_stuffed_with_figs_and_marjoram
      - iot_recipe_chicken_with_butter_and_ginger
      - iot_recipe_chicken_with_cocoa_and_smoked_ham
      - iot_recipe_chocolate_brownies_with_raspberry_reduction
      - iot_recipe_chorizo_tarte_(pissaladiere)
      - iot_recipe_cider_chorizo
      - iot_recipe_coconut_and_curry_vegetable_compote
      - iot_recipe_cod_hearts_with_milk_and_onions
      - iot_recipe_cold_veal_with_tuna_sauce_at_low_temperature
      - iot_recipe_creamy_chocolate_pudding_and_almond_cookies
      - iot_recipe_creamy_potato_and_scampi_pies
      - iot_recipe_crispy_chicken_toast
      - iot_recipe_crock_pot_nachos_and_pulled_chicken
      - iot_recipe_croque_monsieur_with_mushrooms
      - iot_recipe_crumble_with_aubergines_provençal_style
      - iot_recipe_crumbly_citrus_scented_almond_cookies
      - iot_recipe_crunchy_beef_with_peppers
      - iot_recipe_curry_and_burghul_aubergines
      - iot_recipe_curry_flan_with_courgettes_spelt_and_prawns
      - iot_recipe_dill_and_lemon_gilthead_seabream_fillet
      - iot_recipe_dorset_apple_traybake
      - iot_recipe_duchess_potatoes
      - iot_recipe_duck_breast_rolls
      - iot_recipe_duck_breast_salad_with_raspberry_vinegar
      - iot_recipe_duck_terrine_with_glazed_shallots
      - iot_recipe_duck_with_orange_sauce
      - iot_recipe_duck_with_peaches_and_raisins
      - iot_recipe_eggs_in_casserole_with_mushrooms
      - iot_recipe_fabada_asturiana
      - iot_recipe_fillet_of_suckling_pig_in_bread_crust
      - iot_recipe_fillet_of_tub_gurnard_on_stewed_endive_and_malt_vinegar
      - iot_recipe_fillet_of_veal_in_phyllo_crust_and_mashed_pumpkin
      - iot_recipe_fish_tajine
      - iot_recipe_five_spice_suckling_pig
      - iot_recipe_fois_gras_stuffed_mushrooms
      - iot_recipe_fondant_au_chocolat
      - iot_recipe_fried_artichokes_with_wine_and_garlic_sauce
      - iot_recipe_fried_chicken_with_pineapple_and_celery
      - iot_recipe_fried_cubes_of_parmesan_cheese
      - iot_recipe_ginger_and_vinegar_glazed_carrots
      - iot_recipe_gingerbread_crumble
      - iot_recipe_glazed_cucumbers_with_mostarda_and_honey
      - iot_recipe_glazed_monkfish_teriyaki_sauce
      - iot_recipe_glazed_salmon_yakitori
      - iot_recipe_gluten-free_buckwheat_bread
      - iot_recipe_gluten-free_corn_muffins
      - iot_recipe_gluten_free_cauliflower_pizza
      - iot_recipe_glutenfree_bread
      - iot_recipe_gran_cru_chocolate_biscuits
      - iot_recipe_green_peppers_with_herbs_and_cheese
      - iot_recipe_green_yellow_and_red_sweet_and_sour_peppers_with_raisins_and_pine_nuts
      - iot_recipe_guinea_fowl_breast_on_red_potato_mash_and_beetroots
      - iot_recipe_guinea_fowl_glazed_with_orange_and_asparagus
      - iot_recipe_gyros_pitta_rolls
      - iot_recipe_herb_sword_millefeuille
      - iot_recipe_irish_stew
      - iot_recipe_lamb_and_rice_baked_pot-au-feux
      - iot_recipe_lamb_casserole
      - iot_recipe_lamb_fillet_with_cocoa_and_rum
      - iot_recipe_lamb_keema
      - iot_recipe_leeks_stew_with_turmeric
      - iot_recipe_lemon_and_pistachio_grain_cupcakes
      - iot_recipe_lemon_risotto_with_red_prawn_carpaccio
      - iot_recipe_macarons
      - iot_recipe_masala_ratatouille
      - iot_recipe_mash_of_red_lentils_with_sweet_and_sour_onions
      - iot_recipe_mashed_jerusalem_artichoke_and_potatoes
      - iot_recipe_millefeuille_of_tomatoes_and_courgettes
      - iot_recipe_mini_apple_strudel
      - iot_recipe_mini_muffins_with_onion_bacon_and_cheddar
      - iot_recipe_mini_shepherds_pie
      - iot_recipe_mint_stuffed_whole_artichokes
      - iot_recipe_mosaic_of_salmon_and_sole
      - iot_recipe_mushroom_croutons
      - iot_recipe_mushrooms_mini_empanadas
      - iot_recipe_mussels_in_vermouth_reduction
      - iot_recipe_mussels_with_curry
      - iot_recipe_mussels_with_pak_choi
      - iot_recipe_new_york_cheesecake
      - iot_recipe_oatmeal_cookies
      - iot_recipe_octopus_stewed_in_pinot_nero_and_pearl_onions
      - iot_recipe_oil_flat_bread_with_rock_salt
      - iot_recipe_paccheri_stuffed_with_aubergines_and_basil
      - iot_recipe_panbrioche_and_wild_berries_pudding
      - iot_recipe_parmesan_cheese_and_saffron_choux_bun
      - iot_recipe_pavlova_merengue
      - iot_recipe_pears_with_pinot_bianco_and_cinnamon
      - iot_recipe_pepper_fillet_stroganoff
      - iot_recipe_pernod_roasted_scallops_casserole
      - iot_recipe_picana’s_churrasco_cuberoll
      - iot_recipe_piccadilly_tomatoes_stuffed_with_feta_and_mint
      - iot_recipe_pistachio_and_almond_cakes
      - iot_recipe_plum_cake
      - iot_recipe_polenta_and_gorgonzola_timbale
      - iot_recipe_poppy_seeds_rolled_meatballs
      - iot_recipe_pork_cheeks_in_wine_sauce
      - iot_recipe_pork_loin_with_aromatic_milk
      - iot_recipe_pot_au_feu
      - iot_recipe_potato_and_jewish_artichokes_flan
      - iot_recipe_potato_pancake
      - iot_recipe_potato_salad_with_curry_and_paprika_yoghurt
      - iot_recipe_potatoes_and_green_tomatoes_au_gratin
      - iot_recipe_potatoes_stuffed_with_cheese_fondant_and_paprika
      - iot_recipe_prawns_in_white_bread_crust
      - iot_recipe_pumpkin_flan_with_turmeric
      - iot_recipe_purple_potato_dumplings_casserole_with_pepper_flavour
      - iot_recipe_quails_with_sage_and_lemon
      - iot_recipe_quenelle_of_ricotta_cheese_and_marjoram_turnip_tops
      - iot_recipe_red_chicory_with_marinated_beef
      - iot_recipe_red_onions_with_lean_duck
      - iot_recipe_red_rice_prawn_and_black_sesami_croquettes
      - iot_recipe_red_velvet_mini_cupcake
      - iot_recipe_rhubarb_and_raspberry_crumble
      - iot_recipe_rice_and_saffron_pudding
      - iot_recipe_rice_pilaf_with_prawns_and_vegetables
      - iot_recipe_rice_timbales_in_fennel_fondue_with_saffron
      - iot_recipe_ricotta_spinach_and_cinnamon_dumplings_au_gratin
      - iot_recipe_rioja_style_potatoes
      - iot_recipe_risotto_with_pecorino_cheese_and_pears
      - iot_recipe_roasted_ray_with_almond_salad
      - iot_recipe_roasted_stuffed_onions
      - iot_recipe_rolls_of_anchovies_in_herb_crust
      - iot_recipe_rosemary_flat_bread_with_potatoes
      - iot_recipe_round_courgettes_in_pine_nut_beet_compote
      - iot_recipe_rounds_of_polenta_in_artichoke_cream
      - iot_recipe_salmon_and_fennel_pie
      - iot_recipe_salmon_and_leek_quiche
      - iot_recipe_salmon_and_parmesan_mini_muffins
      - iot_recipe_salmon_in_black_sesame_crust
      - iot_recipe_salmon_roses_and_wasabi_mayonnaise
      - iot_recipe_salmon_salad_with_oregano_croutons
      - iot_recipe_salmon_supreme_with_celeriac_mash
      - iot_recipe_salt-baked_roastbeef_at_low_temperature
      - iot_recipe_salt_cod_and_prawn_salad_with_garlic_sauce
      - iot_recipe_savoy_cabbage_rolls_with_asparagus_and_barley
      - iot_recipe_scallop_with_cream_and_potatoes
      - iot_recipe_scampi_borgouignonne_style
      - iot_recipe_seabass_rolls_with_sweet_potatoes
      - iot_recipe_sherry_and_orange_scallops_skewers
      - iot_recipe_shi_drum_pave_in_hazelnut_and_mushroom_crust
      - iot_recipe_shortcrust_pastry
      - iot_recipe_shortcrust_pastry_biscuits_with_cherry_tomatoes_confit
      - iot_recipe_shortcrust_pastry_without_butter
      - iot_recipe_shrimp_and_fresh_garlic_bread_croutons
      - iot_recipe_sliced_beef_with_sweet_and_belgian_potatoes
      - iot_recipe_smoked_mackerel_croquettes
      - iot_recipe_smoked_pork_chops_with_cabbage_and_pearl_onions
      - iot_recipe_spicy_currant_bread
      - iot_recipe_spicy_lamb_peppers_and_cabbage_salad
      - iot_recipe_spicy_quinoa_balls
      - iot_recipe_spicy_stewed_apples
      - iot_recipe_spätzle_with_cheeses
      - iot_recipe_squids_in_armoricain_sauce
      - iot_recipe_squids_stuffed_with_apples_and_parmesan_cheese
      - iot_recipe_stewed_chickpeas_and_chorizo
      - iot_recipe_stir_fried_potatoes_with_herbs
      - iot_recipe_stuffed_phillo_miniquiche
      - iot_recipe_suckling_pig_fillet_in_bacon_strip_and_sesame
      - iot_recipe_suckling_pig_fillet_with_lentils
      - iot_recipe_suckling_pig_fillet_with_wild_herbs_and_fennel
      - iot_recipe_sugar-free_banana_plumcake_and_dates
      - iot_recipe_sweet_and_sour_lamb
      - iot_recipe_sweet_pepper_jam
      - iot_recipe_swordfish_with_chorizo_salad
      - iot_recipe_tajine
      - iot_recipe_tandoori_e_orange_chicken
      - iot_recipe_tangerine_french_clafouti
      - iot_recipe_terrine_of_scallops_and_mint_peas
      - iot_recipe_thai_noodles_with_chicken
      - iot_recipe_thai_style_sauteed_squids_with_basil_and_coriander
      - iot_recipe_the_baguette
      - iot_recipe_tikka_masala_chicken
      - iot_recipe_tomatoes_stuffed_with_lamb_rice_and_peas
      - iot_recipe_trout_and_wood_sorrel_terrine
      - iot_recipe_trout_rolls_with_almonds
      - iot_recipe_tuna_mousse_with_candied_tomatoes
      - iot_recipe_tuna_sesame_and_ginger_bits
      - iot_recipe_turkey_casserole
      - iot_recipe_turnips_and_beetroot_skewers
      - iot_recipe_two_salmon_rillette_and_stewed_shallot
      - iot_recipe_veal_blanquette
      - iot_recipe_veal_liver_with_honey_red_onions_and_sage
      - iot_recipe_veal_rolls_with_asparagus_and_cheese
      - iot_recipe_veal_truffles_in_black_sesame_crust_with_sweet_potato_rosti
      - iot_recipe_vegan_quiche_with_beetroots
      - iot_recipe_vegetable_strudel_with_ginger_and_sesame
      - iot_recipe_vegetarian_stuffed_minipizzas
      - iot_recipe_veggy_vietnamese_rolls
      - iot_recipe_vietnamese_beef_salad_and_noodles
      - iot_recipe_vietnamese_rolls_with_mango_cucumber_and_prawns
      - iot_recipe_white_bread_with_olive_oil
      - iot_recipe_whole_wheat_blueberry_and_yoghurt_muffins
      - iot_recipe_wholegrain_bread
      - iot_recipe_wholemeal_pizza
      - iot_recipe_wild_salmon_fillet_with_apple_sauce_and_potatoes
      - iot_recipe_wild_trout_on_red_turnip_and_garlic_sprouts
      - iot_recipe_wraps_of_turkey_with_spelt_and_shallot_with_balsamic_vinegar
      - multi_level
      - soft_plus
      - tailor_bake_cata
    tempSel:
      max: 280
      min: 50
      step: 5
  stopProgram:
```

The programs that start with "iot_recipe_" there are a standar program with presset time and in the hOn has the complete recipe (ingredients), so, there are useless from HA.

I want get only the "normal" (convention, multi_level, bottom...) and the "iot_guided",  and can sort by first the normal and after the guided would be awesome.
